version: "3"

services:
  front:
    container_name: front
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
 
  mjpg-streamer:
    container_name: streamer
    build:
      context: ./streamer
    devices:
      - /dev/video1
    ports:
      - 8090:8090
    # command: -i "/usr/lib64/input_uvc.so -y -d /dev/video1 -r 320x240 -f 10" -o "/usr/lib64/output_http.so -p 8090 -w /usr/share/mjpeg-streamer/www/"